
[[dependencies]]
  name = "github.com/Sirupsen/logrus"
  version = "v0.11.5"

[[dependencies]]
  branch = "master"
  name = "github.com/go-sql-driver/mysql"

[[dependencies]]
  name = "github.com/namsral/flag"
  version = "v1.7.4-alpha"

[[dependencies]]
  branch = "master"
  name = "github.com/soniah/gosnmp"
