
[[dependencies]]
  branch = "master"
  name = "github.com/Sirupsen/logrus"

[[dependencies]]
  branch = "master"
  name = "github.com/mattn/go-sqlite3"

[[dependencies]]
  branch = "master"
  name = "github.com/soniah/gosnmp"
