
[[dependencies]]
  name = "github.com/Sirupsen/logrus"
  version = "v0.11.5"

[[dependencies]]
  name = "github.com/go-sql-driver/mysql"
  revision = "c775fbc0c7ce5256db87cc1645d60147dbb7ca1c"

[[dependencies]]
  name = "github.com/mattn/go-sqlite3"
  version = "v1.2.0"

[[dependencies]]
  name = "github.com/namsral/flag"
  version = "v1.7.4-alpha"

[[dependencies]]
  branch = "master"
  name = "github.com/soniah/gosnmp"
